# Generated by Django 5.1.3 on 2024-11-06 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Constructo',
            fields=[
                ('cve_const', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('signo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('cve_cuestionario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_corto', models.CharField(max_length=255)),
                ('nombre_largo', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cve_depto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('jefe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('cve_inst', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('federal', models.BooleanField()),
                ('ruta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRespuesta',
            fields=[
                ('cve_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DatosAplicacion',
            fields=[
                ('cve_aplic', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('cve_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departamento')),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instituto')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('cve_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionario')),
                ('cve_const1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const1', to='api.constructo')),
                ('cve_const2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const2', to='api.constructo')),
                ('cve_const3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const3', to='api.constructo')),
                ('cve_const4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const4', to='api.constructo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo_alternativo', models.EmailField(max_length=254)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_resp', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('cve_aplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAplicacion',
            fields=[
                ('cve_score', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('cve_aplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetroChatGPT',
            fields=[
                ('cve_retro', models.AutoField(primary_key=True, serialize=False)),
                ('texto1', models.TextField()),
                ('texto2', models.TextField()),
                ('texto3', models.TextField()),
                ('cve_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scoreaplicacion')),
            ],
        ),
    ]
