# Generated by Django 5.1.3 on 2024-12-02 21:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('cve_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constructo',
            fields=[
                ('cve_const', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('signo', models.CharField(max_length=10)),
                ('acronimo', models.CharField(default='DEFAULT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('cve_cuestionario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_corto', models.CharField(max_length=255)),
                ('nombre_largo', models.CharField(max_length=255)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cve_depto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('jefe', models.CharField(max_length=255)),
                ('plan_estudio', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('cve_inst', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('federal', 'Federal'), ('rural', 'Rural'), ('estatal', 'Estatal')], default='federal', max_length=10)),
                ('ruta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRespuesta',
            fields=[
                ('cve_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission', verbose_name='user permissions')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatosAplicacion',
            fields=[
                ('cve_aplic', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField()),
                ('cuestionario', models.ManyToManyField(to='api.cuestionario')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departamento'),
        ),
        migrations.CreateModel(
            name='IndicadorConstructo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructo')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='constructos',
            field=models.ManyToManyField(through='api.IndicadorConstructo', to='api.constructo'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instituto'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('cve_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto_pregunta', models.TextField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionario')),
                ('cve_const1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const1', to='api.constructo')),
                ('cve_const2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const2', to='api.constructo')),
                ('cve_const3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const3', to='api.constructo')),
                ('cve_const4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='const4', to='api.constructo')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('cve_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('texto', models.FileField(default='csv_files/default.csv', upload_to='csv_files/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cve_aplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('cve_resp', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('cve_aplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreAplicacion',
            fields=[
                ('cve_score', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('cve_aplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetroChatGPT',
            fields=[
                ('cve_retro', models.AutoField(primary_key=True, serialize=False)),
                ('texto1', models.FileField(upload_to='csv_files/')),
                ('texto2', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('texto3', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('cve_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scoreaplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreConstructo',
            fields=[
                ('cve_scoreConstructo', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('constructo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreIndicador',
            fields=[
                ('cve_ScoreIndicador', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
