# Generated by Django 5.1.3 on 2024-11-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constructo',
            name='acronimo',
            field=models.CharField(default='DEFAULT', max_length=10),
        ),
        migrations.AlterField(
            model_name='retrochatgpt',
            name='texto2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retrochatgpt',
            name='texto3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('cve_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cve_aplic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
