# Generated by Django 5.1.3 on 2024-12-03 04:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='scorekey',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='cve_pregunta',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
