# Generated by Django 5.1.3 on 2024-12-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pregunta_scorekey_alter_pregunta_cve_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='api.cuestionario'),
        ),
    ]
