# Generated by Django 5.1.3 on 2024-11-12 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_constructo_acronimo_alter_retrochatgpt_texto2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('constructo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructo')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreConstructo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('constructo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
