# Generated by Django 5.1.3 on 2024-12-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncuestionario',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosaplicacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosaplicacion',
            name='fecha_inicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
