# Generated by Django 5.1.3 on 2024-12-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pregunta_cuestionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreindicador',
            name='constructos',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='api.scoreconstructo'),
        ),
    ]
