# Generated by Django 5.1.3 on 2024-12-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_asignacioncuestionario_fecha_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrochatgpt',
            name='Cuestionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.cuestionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrochatgpt',
            name='aplicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.datosaplicacion'),
            preserve_default=False,
        ),
    ]
