# Generated by Django 5.1.3 on 2024-11-12 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_indicador_scoreconstructo_scoreindicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='constructo',
        ),
        migrations.CreateModel(
            name='IndicadorConstructo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructo')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='constructos',
            field=models.ManyToManyField(through='api.IndicadorConstructo', to='api.constructo'),
        ),
    ]
