# Generated by Django 5.1.3 on 2024-11-12 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_indicador_constructo_indicadorconstructo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosaplicacion',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='scoreaplicacion',
            name='user',
        ),
        migrations.AddField(
            model_name='datosaplicacion',
            name='cuestionario',
            field=models.ManyToManyField(to='api.cuestionario'),
        ),
        migrations.AddField(
            model_name='scoreaplicacion',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
