# Generated by Django 5.1.3 on 2024-11-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_datosaplicacion_cuestionario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituto',
            name='federal',
        ),
        migrations.AddField(
            model_name='instituto',
            name='tipo',
            field=models.CharField(choices=[('federal', 'Federal'), ('rural', 'Rural'), ('estatal', 'Estatal')], default='federal', max_length=10),
        ),
    ]
