# Generated by Django 5.1.3 on 2024-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_datosaplicacion_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacioncuestionario',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asignacioncuestionario',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
