# Generated by Django 5.1.3 on 2024-11-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_instituto_federal_instituto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreconstructo',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreindicador',
            name='score',
            field=models.IntegerField(),
        ),
    ]
