# Generated by Django 5.1.3 on 2024-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_asignacioncuestionario_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='datos_promedios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
