# Generated by Django 5.1.3 on 2024-12-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reporte_datos_promedios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='datos_promedios',
        ),
    ]
