# Generated by Django 5.1.3 on 2024-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_scoreconstructo_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreconstructo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
