# Generated by Django 5.1.3 on 2024-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_scoreconstructo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreindicador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
