# Generated by Django 5.1.3 on 2024-12-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_reporte_datos_promedios'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='datos_promedios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
