# Generated by Django 5.1.3 on 2024-12-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reporte_datos_promedios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='datos_promedios',
        ),
        migrations.AddField(
            model_name='reporte',
            name='promedio_constructos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='promedio_indicadores',
            field=models.TextField(blank=True, null=True),
        ),
    ]
