# Generated by Django 5.1.3 on 2024-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_scoreindicador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='texto',
            field=models.FileField(default='csv_files/default.csv', upload_to='csv_files/'),
        ),
        migrations.AlterField(
            model_name='retrochatgpt',
            name='texto1',
            field=models.FileField(upload_to='csv_files/'),
        ),
        migrations.AlterField(
            model_name='retrochatgpt',
            name='texto2',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
        migrations.AlterField(
            model_name='retrochatgpt',
            name='texto3',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
    ]
