# Generated by Django 5.1.3 on 2024-11-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_reporte_texto_alter_retrochatgpt_texto1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='id_resp',
            new_name='cve_resp',
        ),
        migrations.RenameField(
            model_name='scoreconstructo',
            old_name='id',
            new_name='cve_scoreConstructo',
        ),
        migrations.RenameField(
            model_name='scoreindicador',
            old_name='id',
            new_name='cve_ScoreIndicador',
        ),
    ]
