# Generated by Django 5.1.3 on 2024-12-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reporte_datos_promedios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='promedio_constructos',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='promedio_indicadores',
        ),
    ]
