# Generated by Django 5.1.3 on 2025-01-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_datosaplicacion_reporte_generado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosaplicacion',
            name='nombre_aplicacion',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
