# Generated by Django 5.1.3 on 2025-01-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_datosaplicacion_nombre_aplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosaplicacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='datosaplicacion',
            name='hora',
        ),
    ]
