# Generated by Django 5.1.3 on 2025-01-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_datosaplicacion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.instituto'),
        ),
    ]
