# Generated by Django 5.1.3 on 2025-01-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_reporte_carrera_reporte_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region'),
        ),
    ]
